/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package parking;

import dates.DateFormating;
import employeeScreenGUI.PayParking;
import java.awt.Color;
import java.awt.Image;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import myConnection.MyConnection;

/**
 *
 * @author Rokvic Nkola
 */
public class ParkingSpot extends javax.swing.JFrame {

    /** Creates new form ParkingSpot */
    public ParkingSpot() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        
        Image icon = new ImageIcon(this.getClass().getResource("Parking.png")).getImage();
        this.setIconImage(icon);
        this.setTitle("Parking spot");
    }
    
//    public void setButtonRedAndLblText(){
//        Parking p = new Parking();
//        if (jLabelParkingSpot.getText() == p.jButtonA1.getText()) {
//            p.jButtonA1.setBackground(Color.red);
//            p.jLabelA1.setText("Car with registration number : " + jTextFieldRNumber.getText() + 
//                                                        " is parked at this parking spot : " + " at : " + jLabelStartTime.getText());
//        }else if (jLabelParkingSpot.getText() == p.jButtonA2.getText()) {
//            p.jButtonA2.setBackground(Color.red);
//            p.jLabelA2.setText("Car with registration number : " + jTextFieldRNumber.getText() + 
//                                                        " is parked at this parking spot : " + " at : " + jLabelStartTime.getText());
//        }else if (jLabelParkingSpot.getText() == p.jButtonA3.getText()) {
//            p.jButtonA3.setBackground(Color.red);
//            p.jLabelA3.setText("Car with registration number : " + jTextFieldRNumber.getText() + 
//                                                        " is parked at this parking spot : " + " at : " + jLabelStartTime.getText());
//        }else if (jLabelParkingSpot.getText() == p.jButtonB1.getText()) {
//            p.jButtonB1.setBackground(Color.red);
//            p.jLabelB1.setText("Car with registration number : " + jTextFieldRNumber.getText() + 
//                                                        " is parked at this parking spot : " + " at : " + jLabelStartTime.getText());
//        }else if (jLabelParkingSpot.getText() == p.jButtonB2.getText()) {
//            p.jButtonB2.setBackground(Color.red);
//            p.jLabelB2.setText("Car with registration number : " + jTextFieldRNumber.getText() + 
//                                                        " is parked at this parking spot : " + " at : " + jLabelStartTime.getText());
//        }else if (jLabelParkingSpot.getText() == p.jButtonB3.getText()) {
//            p.jButtonB3.setBackground(Color.red);
//            p.jLabelB3.setText("Car with registration number : " + jTextFieldRNumber.getText() + 
//                                                        " is parked at this parking spot : " + " at : " + jLabelStartTime.getText());
//        }
//    }
    
    public void setLbl(String text){
        jLabelParkingSpot.setText(text);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelParkingSpot = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldRNumber = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.gray);

        jLabelParkingSpot.setText("--------");

        jLabel3.setText("Registratio Number :");

        jButton1.setBackground(java.awt.Color.cyan);
        jButton1.setText("Park Car");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setBackground(java.awt.Color.cyan);
        jButton2.setText("Pay Parking");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabelParkingSpot))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(124, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(57, 57, 57)
                        .addComponent(jButton2)))
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldRNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelParkingSpot, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        Date date = new Date();
        SimpleDateFormat dateForm = new SimpleDateFormat("YY/MM/dd hh:mm:ss");
//        java.sql.Date sqlDate = new java.sql.Date(date.getTime());
        String tt = dateForm.format(date);
//        jLabelStartTime.setText(tt);
//                        setButtonRedAndLblText();
        
        try {
        String query = "INSERT INTO parking(spot_number, car_registration_number, start_time) values(?, ?, ?)";

                    PreparedStatement pst = MyConnection.getInstance()
                            .getConnection()
                            .prepareStatement(query);

                    pst.setString(1, jLabelParkingSpot.getText());
                    pst.setString(2, jTextFieldRNumber.getText());
                    pst.setString(3, tt);

                    int rs = pst.executeUpdate();

                    if (rs > 0) {
                        JOptionPane.showMessageDialog(this, "Car with registration number : " + jTextFieldRNumber.getText() + 
                                                        " is parked at parking spot : " + jLabelParkingSpot.getText() + 
                                                        " at : " + tt);
                        dispose();
                    }

                }catch (Exception e2) {
//                    e2.printStackTrace();
                JOptionPane.showMessageDialog(this, "Car already Parked at this spot!");
//                dispose();
                }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        PayParking pp = new PayParking();
        pp.setLocationRelativeTo(this);
        pp.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParkingSpot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParkingSpot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParkingSpot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParkingSpot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParkingSpot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabelParkingSpot;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldRNumber;
    // End of variables declaration//GEN-END:variables

}
