/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employeeScreenGUI;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import myConnection.MyConnection;

/**
 *
 * @author Rokvic Nkola
 */
public class PayParking extends javax.swing.JFrame {

    /**
     * Creates new form PayParking
     */
    public PayParking() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    private static void find(String join_date, String leave_date) {

        SimpleDateFormat obj = new SimpleDateFormat("MM-dd-yyyy HH:mm:ss");

        try {
            // napravili smo objekte od oba datuma parsiranjem 
            Date date1 = obj.parse(join_date);
            Date date2 = obj.parse(leave_date);
            // milliseconds   
            long time_difference = date2.getTime() - date1.getTime();
//            // days  
//            long days_difference = (time_difference / (1000 * 60 * 60 * 24)) % 365;
//            // years  
//            long years_difference = (time_difference / (1000l * 60 * 60 * 24 * 365));
//            // seconds  
//            long seconds_difference = (time_difference / 1000) % 60;
//            // minutes 
//            long minutes_difference = (time_difference / (1000 * 60)) % 60;

            // razlika u satima  
            long hours_difference = (time_difference / (1000 * 60 * 60)) % 24;

            JOptionPane.showMessageDialog(null, "Your car is parket here for : " + (hours_difference + 1) + " hours "
                    + " and you need to pay : " + ((hours_difference * 250) + 250) + " dinara.");
            
        }catch (ParseException excep) {
            excep.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldRNumber = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.orange);

        jLabel1.setText("Registration number :");

        jButton1.setBackground(java.awt.Color.green);
        jButton1.setText("Pay");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldRNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldRNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:

        try {
            Date date = new Date();
            SimpleDateFormat dateForm = new SimpleDateFormat("YY/MM/dd hh:mm:ss");
            String tt = dateForm.format(date);
//            System.out.println(tt);

            String query = "UPDATE parking SET end_time = ? WHERE car_registration_number = ?";

            PreparedStatement pst = MyConnection.getInstance()
                    .getConnection()
                    .prepareStatement(query);

            pst.setString(1, tt);
            pst.setString(2, jTextFieldRNumber.getText());

            int rs = pst.executeUpdate();
            if (rs > 0) {

                String query2 = "SELECT start_time, end_time FROM parking WHERE car_registration_number = ?";

                PreparedStatement pst2 = MyConnection.getInstance()
                        .getConnection()
                        .prepareStatement(query2);

                pst2.setString(1, jTextFieldRNumber.getText());

                ResultSet rs2 = pst2.executeQuery();
                while (rs2.next()) {
                    String start = rs2.getString(1);
                    String end = rs2.getString(2);

//                    System.out.println(end);
                    find(start, end);

                }

                String query3 = "DELETE FROM parking WHERE car_registration_number = ?";

                PreparedStatement pst3 = MyConnection.getInstance()
                        .getConnection()
                        .prepareStatement(query3);

                pst3.setString(1, jTextFieldRNumber.getText());
                pst3.execute();
                
                dispose();
            }

        } catch (Exception e4) {
//            e4.printStackTrace();
            JOptionPane.showMessageDialog(this, "Car does not exist at our parking.");
//                dispose();
        }

    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayParking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayParking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayParking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayParking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayParking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JTextField jTextFieldRNumber;
    // End of variables declaration//GEN-END:variables
}
